// src/app/homeTexts.ts
// Traductions et libellés de la page d'accueil (sortis de page.tsx pour alléger).

  export const texts = {
    fr: {
      subtitle: 'Espagnol & Catalan — vivez Barcelone pleinement',
      targetLang: 'Je veux apprendre',
      from: 'J\'apprends depuis le',
      selectLevel: 'Ton niveau',
      selectCountry: 'Variante régionale',
      allCountries: '🌍 Toutes les variantes',
      currentSetup: 'Configuration actuelle',
      spanish: '🇪🇸 Espagnol',
      catalan: '🟡 Catalan',
      catalanBadge: 'Nouveau',
      modules: {
        flashcards: { title: 'Flashcards', desc: 'Vocabulaire par pays et niveau' },
        audio: { title: 'Audio', desc: 'Écoute et répète' },
        grammar: { title: 'Grammaire', desc: 'Exercices de grammaire' },
        conjugation: { title: 'Conjugaison', desc: 'Entraîne-toi aux verbes' },
        conversations: { title: 'Conversations', desc: 'Pratique avec l\'IA' },
        audioPro: { title: 'Audio Pro', desc: 'Génère des audios TTS' },
        reading: { title: 'Lecture', desc: 'Textes authentiques' },
        dictee: { title: 'Dictée', desc: 'Écris ce que tu entends' },
      },
      catalanModules: {
        flashcards: { title: 'Flashcards', desc: 'Vocabulaire catalan A1-B1' },
        conjugation: { title: 'Conjugaison', desc: 'Verbes catalans essentiels' },
        grammar: { title: 'Grammaire', desc: 'Articles, ser/estar, négation...' },
        phrases: { title: 'Phrases du quotidien', desc: 'Survie à Barcelone' },
        dictee: { title: 'Dictée', desc: 'Orthographe catalane' },
        pronunciation: { title: 'Prononciation', desc: 'Écoute, répète, obtiens un score' },
      },
      comingSoon: 'Bientôt disponible',
      available: 'Disponible',
    },
    en: {
      subtitle: 'Spanish & Catalan — live Barcelona fully',
      targetLang: 'I want to learn',
      from: 'Learning from',
      selectLevel: 'Your level',
      selectCountry: 'Regional variant',
      allCountries: '🌍 All variants',
      currentSetup: 'Current setup',
      spanish: '🇪🇸 Spanish',
      catalan: '🟡 Catalan',
      catalanBadge: 'New',
      modules: {
        flashcards: { title: 'Flashcards', desc: 'Vocabulary by country & level' },
        audio: { title: 'Audio', desc: 'Listen and repeat' },
        grammar: { title: 'Grammar', desc: 'Grammar exercises' },
        conjugation: { title: 'Conjugation', desc: 'Practice verbs' },
        conversations: { title: 'Conversations', desc: 'Practice with AI' },
        audioPro: { title: 'Audio Pro', desc: 'Generate TTS audio' },
        reading: { title: 'Reading', desc: 'Authentic texts' },
        dictee: { title: 'Dictation', desc: 'Write what you hear' },
      },
      catalanModules: {
        flashcards: { title: 'Flashcards', desc: 'Catalan vocabulary A1-B1' },
        conjugation: { title: 'Conjugation', desc: 'Essential Catalan verbs' },
        grammar: { title: 'Grammar', desc: 'Articles, ser/estar, negation...' },
        phrases: { title: 'Daily Phrases', desc: 'Survive in Barcelona' },
        dictee: { title: 'Dictation', desc: 'Catalan spelling' },
        pronunciation: { title: 'Pronunciation', desc: 'Listen, repeat, get scored' },
      },
      comingSoon: 'Coming soon',
      available: 'Available',
    },
  };

  export const countryLabels = {
    fr: {
      ALL: '🌍 Toutes les variantes',
      spain: '🇪🇸 Espagne (castillan)',
      mexico: '🇲🇽 Mexique',
      argentina: '🇦🇷 Argentine',
      colombia: '🇨🇴 Colombie',
      peru: '🇵🇪 Pérou',
      chile: '🇨🇱 Chili',
      cuba: '🇨🇺 Cuba',
      venezuela: '🇻🇪 Venezuela',
    },
    en: {
      ALL: '🌍 All variants',
      spain: '🇪🇸 Spain (castilian)',
      mexico: '🇲🇽 Mexico',
      argentina: '🇦🇷 Argentina',
      colombia: '🇨🇴 Colombia',
      peru: '🇵🇪 Peru',
      chile: '🇨🇱 Chile',
      cuba: '🇨🇺 Cuba',
      venezuela: '🇻🇪 Venezuela',
    },
  };